# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8853eeec921ed968ab738dfd1b33efc00ba0ad7b799c7c45f518d7f0f5662447d7a22ef1343b9ab29fa6016d3202ebc58d88f964528fe7cfc3f9339a80e9faf

test:
  secret_key_base: 7f86cebb75649ce3309cea1a8892638865b2d16489e908958c46e9317f599306eb1b87567d022443fc240baae7e85960bdef5e5b9d93877285550c930dbe3e9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
